Minor typos
cosmos/sdk-tutorials pull request #1166
Opened 2022-07-13 05:40 UTC by mikedotexe

(Minor) Documentation content update for Authz, Fee Grant, Denoms.

This PR addresses a couple typos I saw while going through these amazing resources.

I also freaked out when saw some environment variables with `_KEY` in them like here:

https://github.com/cosmos/sdk-tutorials/blob/9ff84b94b7f5b4f49750afaefb87386a7931c94e/tutorials/understanding-feegrant/index.md?plain=1#L167

and realized that commands such as `simd keys show alice -a` are just showing the address, not the key. phew.

So I did a little search-and-replace to make `ALICE_KEY` and `BOB_KEY` into `ALICE_ADDRESS` and `BOB_ADDRESS` to add a little clarity.

Then the PR template had a typo and sniped it.

### Change scope

The changes in this Pull Request include (please tick all that apply):

- [X] Small language/grammar fixes
- [ ] Small content fixes 
- [ ] Addition of new content
- [ ] Sample code/command updates
- [ ] Platform fixes
- [ ] Other

2022-07-13 10:15 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ export BOB_ADDRESS=$(simd keys show bob -a)
```suggestion
$ export ALICE=$(simd keys show alice --address)
$ export BOB=$(simd keys show bob --address)
```

What do you think about just using `ALICE` and `BOB` if we use `--address` to make clear?

2022-07-23 20:39 UTC, mikedotexe commented
Thanks for the suggestion there, @xavierlepretre!

2022-07-26 07:56 UTC, xavierlepretre requested changes
That would be where it is used too.

2022-07-26 07:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd tx feegrant grant $ALICE_ADDRESS $BOB_ADDRESS --from alice --spend-limit 100000stake
```suggestion
$ simd tx feegrant grant $ALICE $BOB --from alice --spend-limit 100000stake
```

2022-07-26 07:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd q feegrant grants $BOB_ADDRESS
```suggestion
$ simd q feegrant grants $BOB
```

2022-07-26 07:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd q bank balances $BOB_ADDRESS
```suggestion
$ simd q bank balances $ALICE
$ simd q bank balances $BOB
```

2022-07-26 07:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd tx bank send $BOB_ADDRESS $ALICE_ADDRESS 100kudos --from bob --fee-account $ALICE_ADDRESS --fees 500stake
```suggestion
$ simd tx bank send $BOB $ALICE 100kudos --from bob --fee-account $ALICE --fees 500stake
```

2022-07-26 07:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd q bank balances $BOB_ADDRESS
```suggestion
$ simd q bank balances $ALICE
$ simd q bank balances $BOB
```

2022-07-26 07:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd q feegrant grants $BOB_ADDRESS
```suggestion
$ simd q feegrant grants $BOB
```

2022-07-26 07:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd tx feegrant revoke $ALICE_ADDRESS $BOB_ADDRESS --from alice
```suggestion
$ simd tx feegrant revoke $ALICE $BOB --from alice
```

2022-07-26 07:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd q feegrant grants $BOB_ADDRESS
```suggestion
$ simd q feegrant grants $BOB
```

2022-08-08 15:56 UTC, xavierlepretre requested changes

2022-08-08 15:56 UTC, xavierlepretre commented on tutorials/understanding-feegrant/index.md
> +$ simd q feegrant grants $BOB
```suggestion
$ simd query feegrant grants $BOB
```
That is a correct way of making a query, but for a tutorial, we prefer to have the explicit long form, which makes for easier reading.
The experienced programmer will soon enough be looking for ways to optimise key strokes on their own.

2022-10-10 15:41 UTC, coldice commented
Hey @xavierlepretre, this has been left unattended for a bit - I think the OP's contribution is clear, I do like the simplification of `ALICE_ADDRESS` to just `ALICE`. I follow your comment regarding the verbosity of flags - I propose we adjust that on this PR, deconflict and then get this merged?

2022-10-10 18:36 UTC, xavierlepretre commented
I still want him to unfix the `query` -> `q` he did.

2022-10-13 14:44 UTC, xavierlepretre commented
Replaced by [PR 1241](https://github.com/cosmos/sdk-tutorials/pull/1241).

2022-10-13 14:44 UTC, closed without merging