DRAFT: Small IDA updates based on early C3 feedback
cosmos/sdk-tutorials pull request #1299
Opened 2022-12-07 10:39 UTC by AndrewB9lab

This PR includes minor content updates to the IDA Week 0 and Week 1 material, and corrects a broken external link.

### Change scope

The changes in this Pull Request include (please tick all that apply):

* [X] Small language/grammar fixes
* [X] Small content fixes 
* [ ] Addition of new content
* [ ] Sample code/command updates
* [ ] Platform fixes
* [ ] Other

2022-12-07 14:46 UTC, xavierlepretre requested changes
Minor nit.

2022-12-07 14:46 UTC, xavierlepretre commented on academy/1-what-is-cosmos/1-blockchain-and-cosmos.md
> +To achieve this vision and type of network, the ecosystem relies on an **open-source toolkit**, including the [Inter-Blockchain Communication Protocol (IBC)](http://ibcprotocol.dev/), its implementat
```suggestion
To achieve this vision and type of network, the ecosystem relies on an **open-source toolkit**, including the [Inter-Blockchain Communication Protocol (IBC)](https://ibcprotocol.dev), its implementation in the [Cosmos SDK](https://v1.cosmos.network/sdk), and [Tendermint](https://tendermint.com/) as the base layer providing distributed state finality. A set of modular, adaptable, and interchangeable tools helps not only to quickly create a blockchain but also facilitates the customization of secure and scalable chains.
```

2022-12-09 08:28 UTC, CitMC approved these changes

2022-12-09 08:29 UTC, CitMC approved these changes

2022-12-09 08:41 UTC, CitMC approved these changes

2022-12-12 08:56 UTC, xavierlepretre commented on hands-on-exercise/1-ignite-cli/2-exercise-intro.md
> +The next sections are all about creating a decentralized game of checkers (see rules [here](https://www.ducksters.com/games/checkers_rules.php)) using Ignite CLI and the Cosmos SDK. Each section prog
@AndrewB9lab Idea from a student.

2022-12-21 08:27 UTC, CitMC approved these changes

2023-01-04 11:23 UTC, coldice commented
@xavierlepretre @CitMC is this ready for merge?

2023-01-04 11:25 UTC, xavierlepretre commented
> @xavierlepretre @CitMC is this ready for merge?

For me, yes.

2023-01-05 15:04 UTC, coldice approved these changes

2023-01-05 15:04 UTC, merged