docs: Is update contribution guides
cosmos/sdk-tutorials pull request #1344
Opened 2023-02-16 08:50 UTC by coldice

This PR updates the contribution guidelines and technical documentation.

### Change scope

The changes in this Pull Request include (please tick all that apply):

* [ ] Small language/grammar fixes
* [ ] Small content fixes 
* [ ] Addition of new content
* [ ] Sample code/command updates
* [ ] Platform fixes
* [x] Other

2023-02-16 13:15 UTC, xavierlepretre requested changes

2023-02-16 13:15 UTC, xavierlepretre commented on CONTRIBUTING.md
> +A special note on svg images: They are currently not processed by the asset pipeline therefore svgs must be placed in a static asset folder (`.vuepress/public/`). Landingpage images are stored in the
```suggestion
A special note on svg images: They are currently not processed by the asset pipeline therefore svgs must be placed in a static asset folder (`.vuepress/public/`). Landingpage images are stored in the `lp-images` subfolder. To embed such an image, you can embed `/lp-images/go-lp.svg`, which then points to the file at `.vuepress/public/lp-images/go-lp.svg`.
```

2023-02-16 13:15 UTC, xavierlepretre commented on TECHNICAL-SETUP.md
> +The main config file is located in `.vuepress/config.js`
```suggestion
The main config file is located in `.vuepress/config.js`.
```

2023-02-16 13:15 UTC, xavierlepretre commented on TECHNICAL-SETUP.md
> +Where each module is defined as a children of the root.
```suggestion
Where each module is defined as a child of the root. 
```

2023-02-16 13:15 UTC, xavierlepretre commented on TECHNICAL-SETUP.md
> +* The main landingpages, served under `/`, displays the content defined in [README.MD](README.MD), using the `ModuleLandingPage` layout.
```suggestion
* The main landingpage, served under `/`, displays the content defined in [README.MD](README.MD), using the `ModuleLandingPage` layout.
```

2023-02-16 13:15 UTC, xavierlepretre commented on TECHNICAL-SETUP.md
> +* Module landingpages (Like the [what is cosmos lp](academy/1-what-is-cosmos/index.md)) are stored as `index.md` file in a subfolder.
```suggestion
* Module landingpages (Like [what is cosmos lp](academy/1-what-is-cosmos/index.md)) are stored as an `index.md` file in a subfolder.
```

2023-02-16 13:15 UTC, xavierlepretre commented on TECHNICAL-SETUP.md
> +Module landingpages can use implement the  `<card-module/>` for an optional display of children pages within that content folder.
```suggestion
Module landingpages can implement the `<card-module/>` for an optional display of children pages within that content folder.
```

2023-02-28 10:06 UTC, coldice commented on CONTRIBUTING.md
> +- To setup the portal lcoally, please follow the [Local setup and build](TECHNICAL-SETUP.md#local-setup-and-build) guide in the [TECHNICAL SETUP](TECHNICAL-SETUP.md) document. You might also want to
@xavierlepretre @CitMC on the word _setup_ I have been following this: https://grammarist.com/spelling/set-up-vs-setup/ which points me to use set up here?

2023-02-28 10:08 UTC, coldice commented on CONTRIBUTING.md
> +- To setup the portal lcoally, please follow the [Local setup and build](TECHNICAL-SETUP.md#local-setup-and-build) guide in the [TECHNICAL SETUP](TECHNICAL-SETUP.md) document. You might also want to
Agree on adding the second sentence part 👍

2023-02-28 10:20 UTC, xavierlepretre commented on CONTRIBUTING.md
> +- To setup the portal lcoally, please follow the [Local setup and build](TECHNICAL-SETUP.md#local-setup-and-build) guide in the [TECHNICAL SETUP](TECHNICAL-SETUP.md) document. You might also want to
To set up is the infinitive form of the verb, so 2 words.

2023-03-22 17:12 UTC, CitMC approved these changes
Added minor edits

2023-03-22 17:13 UTC, CitMC commented
@coldice I believe it is ready to be merged. Added some minor edits.

2023-04-27 08:48 UTC, CitMC commented
@coldice isn't this ready to be merged?

2023-05-17 10:15 UTC, merged