Add a Docker checkers standalone
cosmos/sdk-tutorials pull request #1368
Opened 2023-04-06 20:50 UTC by xavierlepretre

Up to now, the CosmJS hands-on exercise was asking the student to run Ignite to test. This is heavy and works for IDA students. On the other hand, it risks discouraging purely Javascript developers that cannot be bothered with the Go code.

This PR introduces and makes use of the new _standalone_ checkers + faucet so that Javascript developers can be up and running fast:

* 1 Dockerfile that can be downloaded with `curl`.
* 1 checkers Docker image of 85 MB to build in 10 minutes (with about 300 MB of downloads I think)
* 1 faucet Docker image of 210 MB to build in 1 minute.

### R1: Internal review (B9lab)

- Technical review
  - [ ] requested
  - [ ] completed
- Language review
  - [ ] requested
  - [ ] completed

### R2: External review

- Technical review
  - [ ] requested
  - [ ] completed
- Language review
  - [ ] requested
  - [ ] completed

### R3: Internal QA review (B9lab)

- Technical review
  - [ ] requested
  - [ ] completed
- Language review
  - [ ] requested
  - [ ] completed

### R4: Final external QA review

- Technical review
  - [ ] requested
  - [ ] completed
- Language review
  - [ ] requested
  - [ ] completed

### RC: Release Candidate

- [ ] Ready to be merged

2023-04-11 12:08 UTC, murataniloener approved these changes
lgtm, nice work! Just left minor comments about the URL to fetch the Dockerfile.

2023-04-11 13:03 UTC, xavierlepretre commented on hands-on-exercise/3-cosmjs-adv/1-cosmjs-objects.md
> +       $ curl -O https://github.com/cosmos/b9-checkers-academy-draft/blob/run-prod/Dockerfile-standalone
Yes 🤦

2023-04-11 13:03 UTC, xavierlepretre commented on hands-on-exercise/3-cosmjs-adv/1-cosmjs-objects.md
> +    --network checkers-net \
In fact, it is created right at this time. It is a transient one.

2023-04-11 13:04 UTC, xavierlepretre commented on hands-on-exercise/3-cosmjs-adv/1-cosmjs-objects.md
> +1. A Docker network was created with the name `checkers-net`. If another container is started in this network, all ports are mutually accessible.
Ooh let me check again.

2023-04-19 17:43 UTC, AndrewB9lab requested changes

2023-04-19 18:52 UTC, xavierlepretre commented on hands-on-exercise/4-run-in-prod/1-run-prod-docker.md
> +The CosmJS exercise already references this standalone `Dockerfile` so this is a circular reference. You can still on it on your own now.
Oh "work on it"

2023-04-20 08:19 UTC, AndrewB9lab approved these changes
Language review complete.

2023-05-02 08:55 UTC, samricotta commented on hands-on-exercise/3-cosmjs-adv/1-cosmjs-objects.md
> +* If you arrived here and are only focussed on learning CosmJS, it is possible to abstract away niceties of the running chain in a minimal package. For this, you need Docker and to create an image:
```suggestion
* If you arrived here and are only focused on learning CosmJS, it is possible to abstract away niceties of the running chain in a minimal package. For this, you need Docker and to create an image:
```

2023-05-04 23:29 UTC, coldice approved these changes

2023-05-04 23:29 UTC, merged