Update voter tutorial
cosmos/sdk-tutorials pull request #492
Opened 2021-01-09 00:53 UTC by Tosch110

Update voter tutorial to Starport v0.13.1

Closes #446

2021-01-10 07:53 UTC, fadeev requested changes
The frontend has to be fixed so that it's usable both locally and on Gitpod.

## vue/src/components/PollForm.vue

```
<script>
import * as sp from "@tendermint/vue";
export default {
  components: { ...sp },
  data() {
    return {
      title: "",
      options: []
    };
  },
  methods: {
    add() {
      this.options = [...this.options, { title: "" }];
    },
    async submit() {
      const payload = {
        type: "poll",
        module: "voter",
        body: {
          title: this.title,
          options: this.options.map(o => o.title)
        }
      };
      await this.$store.dispatch("cosmos/entitySubmit", payload);
        await this.$store.dispatch("cosmos/entityFetch", payload);
    }
  }
};
</script>
```

Delete `vue/src/store/app.js`.

## vue/src/store/index.js

```
import Vue from "vue";
import Vuex from "vuex";
import axios from "axios";
import cosmos from "@tendermint/vue/src/store/cosmos.js";

Vue.use(Vuex);

export default new Vuex.Store({
  modules: { cosmos },
});
```

## vue/src/App.vue

```
<script>
export default {
  created() {
    this.$store.dispatch("cosmos/init");
    this.$store.dispatch("cosmos/entityFetch", {type: "poll", module: "voter"});
    this.$store.dispatch("cosmos/entityFetch", {type: "vote", module: "voter"});
  },
};
</script>
```

## vue/src/components/PollList.vue

```
<script>
import * as sp from "@tendermint/vue";
import AppRadioItem from "./AppRadioItem";
import AppText from "./AppText";
import {countBy } from "lodash"
export default {
  components: { AppText, AppRadioItem, ...sp },
  data() {
    return {
      selected: ""
    };
  },
  computed: {
    polls() {
      return this.$store.state.cosmos.data["voter/poll"] || [];
    },
    votes() {
      return this.$store.state.cosmos.data["voter/vote"] || [];
    }
  },
  methods: {
    results(id) {
      const results = this.votes.filter(v => v.pollID === id);
      return countBy(results, "value");
    },
    async submit(pollID, value) {
      const type = { type: "vote" };
      const body = { pollID, value };
      await this.$store.dispatch("cosmos/entitySubmit", { ...type, module:"voter", body });
      await this.$store.dispatch("cosmos/entityFetch", {...type, module: "voter"});
    }
  }
};
</script>
```

## vue/src/main.js

```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: (h) => h(App),
}).$mount("#app");
```

Basically, we use `cosmos/entitySubmit` and pass `module: "voter"`. No longer need `app.js` and no changes to the store are required.

2021-01-10 08:11 UTC, fadeev commented
@Tosch110 here is the finished state of the tutorial that works for me:

https://github.com/fadeev/starport/tree/develop/docs/voter

2021-01-11 09:00 UTC, Tosch110 commented on voter/voter/x/voter/client/cli/txPoll.go
> +		Args:  cobra.ExactArgs(2),
Addressed

2021-01-11 09:00 UTC, Tosch110 commented on voter/voter/x/voter/client/cli/txPoll.go
> +		Args:  cobra.ExactArgs(3),
Addressed

2021-01-11 09:49 UTC, fadeev approved these changes
Great work, @Tosch110! 🦖

2021-01-11 09:50 UTC, merged