Add instructions for initializing vue
cosmos/sdk-tutorials pull request #758
Opened 2021-07-11 16:30 UTC by lilamila

2021-07-12 23:32 UTC, barriebyron commented
hi @lilamila thanks for your first-time contribution to making our tutorials more awesome. I don't know the technical substance behind your suggested changes, I am asking Denis... stay tuned!

2021-07-12 23:40 UTC, toschdev commented
In version 0.15.1 the frontend should be running with `starport serve`. Visit localhost:1317
With v0.16 and higher, it needs to be executed manually.

2021-07-13 18:43 UTC, barriebyron commented
@lilamila thanks for this PR, but no changes are required for the current Starport version required in this tutorial. You'll see this change come in at later Starport versions. Keep watching and letting us know when we can serve you better.

2021-07-13 18:44 UTC, barriebyron requested changes
this change is required only at Starport v0.16 and higher. Let's not make this change now.

2021-07-13 19:41 UTC, fadeev commented on voter/index.md
> +```
v0.15 runs the front-end automatically.

2021-07-13 23:07 UTC, closed without merging