docs: Module 5 CosmWasm (B9lab updates 4-1)
cosmos/sdk-tutorials pull request #844
Opened 2021-10-20 17:27 UTC by coldice

Docs content update for Module 5 (Running my own chain), Section _CosmWasm_ - part of the [b9lab-content](https://github.com/cosmos/sdk-tutorials/tree/master/b9lab-content).

### Content state

**✔️ Completed**

### Technical review

- [x] requested
- [ ] completed

### Language review

- [ ] requested
- [ ] completed

2021-10-21 08:03 UTC, orkunkl commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +$ cd cw-examples/contracts/
```suggestion
$ cd cw-contracts/contracts/
```

2021-10-21 08:03 UTC, orkunkl commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +  cosmwasm/rust-optimizer:0.11.5
```suggestion
  cosmwasm/rust-optimizer:0.12.3
```

2021-10-21 08:10 UTC, orkunkl commented
@kaymakf can you dry run the commands in the document?

2021-10-21 11:19 UTC, kaymakf requested changes

2021-10-21 11:19 UTC, kaymakf commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +$ git checkout v0.18.0
```suggestion
$ git checkout v0.18.0
$ make install
```

2021-10-21 11:19 UTC, kaymakf commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +$ export COSMOVISOR_HOME=/root/.wasmd
```suggestion
$ export COSMOVISOR_HOME=$HOME/.wasmd
```

2021-10-21 11:19 UTC, kaymakf commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +$ cd cw-examples/contracts/
```suggestion
$ cd cw-contracts/contracts/nameservice/
```

2021-10-21 11:19 UTC, kaymakf commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +$ wasmd tx wasm store artifacts/cw_nameservice.wasm --from wallet --node $RPC --chain-id pebblenet-1 --gas-prices 0.001upebble --gas auto --gas-adjustment 1.3
```suggestion
$ RES=$(wasmd tx wasm store artifacts/cw_nameservice.wasm --from wallet --node $RPC --chain-id pebblenet-1 --gas-prices 0.001upebble --gas auto --gas-adjustment 1.3)
$ CODE_ID=$(echo $RES | jq -r '.logs[0].events[-1].attributes[0].value')
```
might be easier to read

2021-11-22 17:45 UTC, CitMC commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +# CosmWasm
I believe this is a very good idea! :) Just to make sure everything is always in its most recent version.

2021-11-24 10:22 UTC, orkunkl commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +# CosmWasm
We have switched to `sandynet`. Let's setup the script for making everything easy for you guys.

2021-11-24 10:25 UTC, orkunkl commented on b9lab-content/5-my-own-chain/05-cosmwasm.md
> +# CosmWasm
We don't have a one pager like this rather a directory. https://github.com/InterWasm/docs/tree/main/docs/02-getting-started.
Re: compatibility, I don't think there will be a problem.

2021-11-25 10:49 UTC, coldice commented
Merged in b9lab-content-updates-rc1 (no diff to this branch)

2021-11-25 10:49 UTC, closed without merging