WIP: docs: Module 3 IBC - code sample integration (B9lab updates 2-6-a)
cosmos/sdk-tutorials pull request #851
Opened 2021-11-02 21:26 UTC by coldice

Docs content update for Module 3, Section _IBC_ - part of the [b9lab-content](https://github.com/cosmos/sdk-tutorials/tree/master/b9lab-content).

This PR adds code samples to the content. The code shown here is taken from the [code example repo](https://github.com/cosmos/b9-checkers-academy-draft/) and has been hardly adjusted. The repo has been reviewed so no need to review it here. What we are looking for is to make sure that the introductory texts are not misleading or even downright wrong.

### Content state

**✔️ Completed**

### Technical review
- [x] requested
- [ ] completed

### Language review
- [ ] requested
- [ ] completed

2021-11-15 19:01 UTC, nooomski requested changes
Looks great! There's still an open TODO on line 152 & 161. Otherwise mostly small stuff.

2021-11-18 15:50 UTC, CitMC commented on b9lab-content/3-main-concepts/16-ibc.md
> +
Will take care of this.

2021-11-18 15:50 UTC, CitMC commented on b9lab-content/3-main-concepts/16-ibc.md
>  ## Components
I'll look into it.

2021-11-18 15:50 UTC, CitMC commented on b9lab-content/3-main-concepts/16-ibc.md
I'll make sure it will be changed.

2021-11-18 15:52 UTC, CitMC commented on b9lab-content/3-main-concepts/16-ibc.md
>  <!-- TODO -->
Will do.

2021-11-22 13:37 UTC, CitMC commented on b9lab-content/3-main-concepts/16-ibc.md
>  <!-- TODO -->
I included it all properly in a fitting Highlight Box.

2021-11-24 00:19 UTC, merged